Repository chu-aie/cobots-2024, pull requests merged in 2024-05, with the labels that each got.

#56 Entelecheia/issue54
  src/cobots2024/book/_toc.yml
  src/cobots2024/book/week13/figs/move_group.png
  src/cobots2024/book/week13/figs/mtc_example.png
  src/cobots2024/book/week13/figs/mtc_show_stages.gif
  src/cobots2024/book/week13/figs/mtc_stage_types.png
  src/cobots2024/book/week13/figs/planning_scene_monitor.svg
  src/cobots2024/book/week13/index.md
  src/cobots2024/book/week13/move_group.md
  src/cobots2024/book/week13/moveit_task_constructor.md
  src/cobots2024/book/week13/planning_scene_monitor.md
  src/cobots2024/book/week13/trajectory_processing.md
Labels: documentation, Review effort [1-5]: 2

#58 Entelecheia/issue57
  src/cobots2024/book/_toc.yml
  src/cobots2024/book/week14/index.md
  src/cobots2024/book/week14/jupyter_notebook_prototyping/CMakeLists.txt
  src/cobots2024/book/week14/jupyter_notebook_prototyping/config/jupyter_notebook_prototyping.rviz
  src/cobots2024/book/week14/jupyter_notebook_prototyping/config/jupyter_notebook_prototyping.yaml
  src/cobots2024/book/week14/jupyter_notebook_prototyping/index.md
  src/cobots2024/book/week14/jupyter_notebook_prototyping/launch/jupyter_notebook_prototyping.launch.py
  src/cobots2024/book/week14/jupyter_notebook_prototyping/src/moveit_notebook_tutorial.ipynb
  src/cobots2024/book/week14/motion_planning_python_api/CMakeLists.txt
  src/cobots2024/book/week14/motion_planning_python_api/config/motion_planning_python_api_tutorial.rviz
  src/cobots2024/book/week14/motion_planning_python_api/config/motion_planning_python_api_tutorial.yaml
  src/cobots2024/book/week14/motion_planning_python_api/index.md
  src/cobots2024/book/week14/motion_planning_python_api/launch/motion_planning_python_api_tutorial.launch.py
  src/cobots2024/book/week14/motion_planning_python_api/scripts/motion_planning_python_api_planning_scene.py
  src/cobots2024/book/week14/motion_planning_python_api/scripts/motion_planning_python_api_tutorial.py
Labels: documentation, enhancement, Review effort [1-5]: 4

#62 Create 12w homework
  src/cobots2024/book/projects/202021029/12w homework
Labels: documentation, Review effort [1-5]: 1

#61 Update index.md
  src/cobots2024/book/projects/202021024/index.md
Labels: documentation, Review effort [1-5]: 1

#59 fix: update homework by ypilseong
  src/cobots2024/book/projects/202121010/figs/openGL_error.png
  src/cobots2024/book/projects/202121010/figs/opengl_version.png
  src/cobots2024/book/projects/202121010/figs/turtlesim.png
  src/cobots2024/book/projects/202121010/homework.md
Labels: documentation, Review effort [1-5]: 1
