Repository chu-aie/cobots-2024, pull requests merged in 2024-06, with the labels that each got.

#66 Update index.md
  src/cobots2024/book/projects/202021038/index.md
Labels: documentation, Review effort [1-5]: 1

#75 Update index.md
  src/cobots2024/book/projects/202021024/index.md
Labels: documentation, enhancement, Review effort [1-5]: 3

#76 Update Final Project.md
  src/cobots2024/book/projects/202221014/index.md
  src/cobots2024/book/projects/202221014/jupyter_notebook_prototyping.launch.py
  src/cobots2024/book/projects/202221014/ros2_Project2_gyubeom.py
Labels: documentation, enhancement, Review effort [1-5]: 4

#77 Ypilseong/project patch 4
  src/cobots2024/book/projects/202121010/index.md
  src/cobots2024/book/projects/202121010/jupyter_notebook_prototyping.launch.py
  src/cobots2024/book/projects/202121010/ros2_project_ypilseong.ipynb
Labels: documentation, enhancement, Review effort [1-5]: 4
